spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:13271/railway
    username: postgres
    password: HlKiKkDWAQlHnfrqoXyfdhnjkVoiJaCz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8085