#spring:
#  application:
#    name: api-gateway
#  config:
#    import: "optional:configserver:http://localhost:8088"
server:
  port: 8888
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/books/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2



