
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:54578/railway
    username: postgres
    password: fUOEYQwFdWztnsQnnbwaiihbTDxdOilm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: localhost:9094
server:
  port: 8087

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    hashSecret: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8087/payment/vnpay-callback
    version: 2.1.0
    command: pay
    order_type: others