
spring:
  application:
    name: book-service
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:13271/railway
    username: postgres
    password: HlKiKkDWAQlHnfrqoXyfdhnjkVoiJaCz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: local
server:
  port: 8081


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


cloudinary:
    cloud-name: dxkr1bbdp
    api-key: 969818675411756
    api-secret: myZphrJdZ4j7b8r29f1

google:
  gemini:
    apiKey: AIzaSyDb3vvCgGLobKoUP9ukVYviavqCa9tcYg0