
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:13271/railway
    username: postgres
    password: HlKiKkDWAQlHnfrqoXyfdhnjkVoiJaCz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: kafka_microservice:9092
server:
  port: 8082


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server-registry:8761/eureka
  instance:
    prefer-ip-address: true
